### ISSUE TITLE
Super Jump screen loop bug, plus hammer enemy softlock

### ISSUE THREAD

**Issue by KCEXE** [becored/WL4_PT#1]
Hello there! I really enjoyed playing WL4 again with the Pizza Tower style moves, but I did run into two griping issues during my run...

Whenever Wario does his Super Jump in small rooms, he warps through the screen vertically in a loop; as demonstrated here:

![sjumpbug1](https://user-images.githubusercontent.com/29708975/233432246-dc48c220-9576-43af-bd44-db2eaed1620c.gif)
(Moving around for a bit can get you out of this though!)

There is also a softlock with hammer enemies when running mach speed, putting Spring Wario in a broken state; as seen here:

![sjumpbug2](https://user-images.githubusercontent.com/29708975/233432373-d83aaee6-23ba-4f4c-b59a-1c5653f672cd.gif)
(Can't get out of this one, sadly. Forcing you to exit the stage.)

Otherwise, the hack was pretty solid! Really gave the game a whole new spin 😊

**Comment by becored** [comment]
Thank you for letting me know about the issues, also glad you enjoyed it!

> Whenever Wario does his Super Jump in small rooms, he warps through the screen vertically in a loop  

This is how the camera works for small rooms in the vanilla, so the best solution would be placing the ceilings for every room.    
However, this patch was initially made for the customized levels and was not supposed to apply to the vanilla (I knew it would completely mess up the level designs), so I'm not going to try fixing this for now.  

> There is also a softlock with hammer enemies when running mach speed, putting Spring Wario in a broken state  

Confirmed this was a bug with my patch. I've fixed it in v1.1 release.
